FROM python:3.12-slim AS builder

WORKDIR /app

RUN python -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt .

RUN  pip install --no-cache-dir -r requirements.txt
#===========================
FROM python:3.12-slim

WORKDIR /app

RUN addgroup --system python && \
    adduser --system --disabled-password --ingroup python python && \
    chown python:python /app
USER python

COPY --chown=python:python --from=builder /app/venv/ ./venv

COPY --chown=python:python . .

ENV PATH="/app/venv/bin:$PATH"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 